spring.datasource.url=jdbc:postgresql://localhost:5432/users
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=${MQ_USER}
spring.rabbitmq.password=${MQ_PASS}

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${USER_EMAIL}
spring.mail.password=${PASSWORD_EMAIL}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
